/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KamchatkaIndexRouteImport } from './routes/kamchatka.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as KamchatkaSlugRouteImport } from './routes/kamchatka.$slug'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as AdminSiteRouteImport } from './routes/admin.site'
import { Route as AdminRoomsRouteImport } from './routes/admin.rooms'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminGuestsRouteImport } from './routes/admin.guests'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminSiteIndexRouteImport } from './routes/admin.site.index'
import { Route as BookingVoucherIdRouteImport } from './routes/booking.voucher.$id'
import { Route as BookingPayIdRouteImport } from './routes/booking.pay.$id'
import { Route as BookingChatIdRouteImport } from './routes/booking.chat.$id'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api/telegram/webhook'
import { Route as ApiPublicTravellineTestRouteImport } from './routes/api/public/travelline-test'
import { Route as ApiPublicAlfaCallbackRouteImport } from './routes/api/public/alfa-callback'
import { Route as ApiInternalCronTlSyncRouteImport } from './routes/api/internal/cron-tl-sync'
import { Route as ApiInternalCronRemindersRouteImport } from './routes/api/internal/cron-reminders'
import { Route as AdminSiteServicesRouteImport } from './routes/admin.site.services'
import { Route as AdminSiteHomeRouteImport } from './routes/admin.site.home'
import { Route as AdminSiteAboutRouteImport } from './routes/admin.site.about'
import { Route as ApiPublicVoucherIdRouteImport } from './routes/api/public/voucher.$id'

const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamchatkaIndexRoute = KamchatkaIndexRouteImport.update({
  id: '/kamchatka/',
  path: '/kamchatka/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const KamchatkaSlugRoute = KamchatkaSlugRouteImport.update({
  id: '/kamchatka/$slug',
  path: '/kamchatka/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookingRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuestsRoute = AdminGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteIndexRoute = AdminSiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSiteRoute,
} as any)
const BookingVoucherIdRoute = BookingVoucherIdRouteImport.update({
  id: '/voucher/$id',
  path: '/voucher/$id',
  getParentRoute: () => BookingRoute,
} as any)
const BookingPayIdRoute = BookingPayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => BookingRoute,
} as any)
const BookingChatIdRoute = BookingChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => BookingRoute,
} as any)
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram/webhook',
  path: '/api/telegram/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTravellineTestRoute = ApiPublicTravellineTestRouteImport.update({
  id: '/api/public/travelline-test',
  path: '/api/public/travelline-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlfaCallbackRoute = ApiPublicAlfaCallbackRouteImport.update({
  id: '/api/public/alfa-callback',
  path: '/api/public/alfa-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCronTlSyncRoute = ApiInternalCronTlSyncRouteImport.update({
  id: '/api/internal/cron-tl-sync',
  path: '/api/internal/cron-tl-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCronRemindersRoute =
  ApiInternalCronRemindersRouteImport.update({
    id: '/api/internal/cron-reminders',
    path: '/api/internal/cron-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSiteServicesRoute = AdminSiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminSiteRoute,
} as any)
const AdminSiteHomeRoute = AdminSiteHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminSiteRoute,
} as any)
const AdminSiteAboutRoute = AdminSiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminSiteRoute,
} as any)
const ApiPublicVoucherIdRoute = ApiPublicVoucherIdRouteImport.update({
  id: '/api/public/voucher/$id',
  path: '/api/public/voucher/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/rooms': typeof RoomsRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/wellness': typeof WellnessRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/site': typeof AdminSiteRouteWithChildren
  '/booking/success': typeof BookingSuccessRoute
  '/kamchatka/$slug': typeof KamchatkaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/kamchatka/': typeof KamchatkaIndexRoute
  '/admin/site/about': typeof AdminSiteAboutRoute
  '/admin/site/home': typeof AdminSiteHomeRoute
  '/admin/site/services': typeof AdminSiteServicesRoute
  '/api/internal/cron-reminders': typeof ApiInternalCronRemindersRoute
  '/api/internal/cron-tl-sync': typeof ApiInternalCronTlSyncRoute
  '/api/public/alfa-callback': typeof ApiPublicAlfaCallbackRoute
  '/api/public/travelline-test': typeof ApiPublicTravellineTestRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/booking/chat/$id': typeof BookingChatIdRoute
  '/booking/pay/$id': typeof BookingPayIdRoute
  '/booking/voucher/$id': typeof BookingVoucherIdRoute
  '/admin/site/': typeof AdminSiteIndexRoute
  '/api/public/voucher/$id': typeof ApiPublicVoucherIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/booking': typeof BookingRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/rooms': typeof RoomsRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/wellness': typeof WellnessRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/booking/success': typeof BookingSuccessRoute
  '/kamchatka/$slug': typeof KamchatkaSlugRoute
  '/admin': typeof AdminIndexRoute
  '/kamchatka': typeof KamchatkaIndexRoute
  '/admin/site/about': typeof AdminSiteAboutRoute
  '/admin/site/home': typeof AdminSiteHomeRoute
  '/admin/site/services': typeof AdminSiteServicesRoute
  '/api/internal/cron-reminders': typeof ApiInternalCronRemindersRoute
  '/api/internal/cron-tl-sync': typeof ApiInternalCronTlSyncRoute
  '/api/public/alfa-callback': typeof ApiPublicAlfaCallbackRoute
  '/api/public/travelline-test': typeof ApiPublicTravellineTestRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/booking/chat/$id': typeof BookingChatIdRoute
  '/booking/pay/$id': typeof BookingPayIdRoute
  '/booking/voucher/$id': typeof BookingVoucherIdRoute
  '/admin/site': typeof AdminSiteIndexRoute
  '/api/public/voucher/$id': typeof ApiPublicVoucherIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/booking': typeof BookingRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/rooms': typeof RoomsRoute
  '/services': typeof ServicesRoute
  '/signup': typeof SignupRoute
  '/wellness': typeof WellnessRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/guests': typeof AdminGuestsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/site': typeof AdminSiteRouteWithChildren
  '/booking/success': typeof BookingSuccessRoute
  '/kamchatka/$slug': typeof KamchatkaSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/kamchatka/': typeof KamchatkaIndexRoute
  '/admin/site/about': typeof AdminSiteAboutRoute
  '/admin/site/home': typeof AdminSiteHomeRoute
  '/admin/site/services': typeof AdminSiteServicesRoute
  '/api/internal/cron-reminders': typeof ApiInternalCronRemindersRoute
  '/api/internal/cron-tl-sync': typeof ApiInternalCronTlSyncRoute
  '/api/public/alfa-callback': typeof ApiPublicAlfaCallbackRoute
  '/api/public/travelline-test': typeof ApiPublicTravellineTestRoute
  '/api/telegram/webhook': typeof ApiTelegramWebhookRoute
  '/booking/chat/$id': typeof BookingChatIdRoute
  '/booking/pay/$id': typeof BookingPayIdRoute
  '/booking/voucher/$id': typeof BookingVoucherIdRoute
  '/admin/site/': typeof AdminSiteIndexRoute
  '/api/public/voucher/$id': typeof ApiPublicVoucherIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/booking'
    | '/contacts'
    | '/login'
    | '/rooms'
    | '/services'
    | '/signup'
    | '/wellness'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/guests'
    | '/admin/inbox'
    | '/admin/notifications'
    | '/admin/rooms'
    | '/admin/site'
    | '/booking/success'
    | '/kamchatka/$slug'
    | '/admin/'
    | '/kamchatka/'
    | '/admin/site/about'
    | '/admin/site/home'
    | '/admin/site/services'
    | '/api/internal/cron-reminders'
    | '/api/internal/cron-tl-sync'
    | '/api/public/alfa-callback'
    | '/api/public/travelline-test'
    | '/api/telegram/webhook'
    | '/booking/chat/$id'
    | '/booking/pay/$id'
    | '/booking/voucher/$id'
    | '/admin/site/'
    | '/api/public/voucher/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/booking'
    | '/contacts'
    | '/login'
    | '/rooms'
    | '/services'
    | '/signup'
    | '/wellness'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/guests'
    | '/admin/inbox'
    | '/admin/notifications'
    | '/admin/rooms'
    | '/booking/success'
    | '/kamchatka/$slug'
    | '/admin'
    | '/kamchatka'
    | '/admin/site/about'
    | '/admin/site/home'
    | '/admin/site/services'
    | '/api/internal/cron-reminders'
    | '/api/internal/cron-tl-sync'
    | '/api/public/alfa-callback'
    | '/api/public/travelline-test'
    | '/api/telegram/webhook'
    | '/booking/chat/$id'
    | '/booking/pay/$id'
    | '/booking/voucher/$id'
    | '/admin/site'
    | '/api/public/voucher/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/booking'
    | '/contacts'
    | '/login'
    | '/rooms'
    | '/services'
    | '/signup'
    | '/wellness'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/guests'
    | '/admin/inbox'
    | '/admin/notifications'
    | '/admin/rooms'
    | '/admin/site'
    | '/booking/success'
    | '/kamchatka/$slug'
    | '/admin/'
    | '/kamchatka/'
    | '/admin/site/about'
    | '/admin/site/home'
    | '/admin/site/services'
    | '/api/internal/cron-reminders'
    | '/api/internal/cron-tl-sync'
    | '/api/public/alfa-callback'
    | '/api/public/travelline-test'
    | '/api/telegram/webhook'
    | '/booking/chat/$id'
    | '/booking/pay/$id'
    | '/booking/voucher/$id'
    | '/admin/site/'
    | '/api/public/voucher/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  BookingRoute: typeof BookingRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  LoginRoute: typeof LoginRoute
  RoomsRoute: typeof RoomsRoute
  ServicesRoute: typeof ServicesRoute
  SignupRoute: typeof SignupRoute
  WellnessRoute: typeof WellnessRoute
  KamchatkaSlugRoute: typeof KamchatkaSlugRoute
  KamchatkaIndexRoute: typeof KamchatkaIndexRoute
  ApiInternalCronRemindersRoute: typeof ApiInternalCronRemindersRoute
  ApiInternalCronTlSyncRoute: typeof ApiInternalCronTlSyncRoute
  ApiPublicAlfaCallbackRoute: typeof ApiPublicAlfaCallbackRoute
  ApiPublicTravellineTestRoute: typeof ApiPublicTravellineTestRoute
  ApiTelegramWebhookRoute: typeof ApiTelegramWebhookRoute
  ApiPublicVoucherIdRoute: typeof ApiPublicVoucherIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamchatka/': {
      id: '/kamchatka/'
      path: '/kamchatka'
      fullPath: '/kamchatka/'
      preLoaderRoute: typeof KamchatkaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/kamchatka/$slug': {
      id: '/kamchatka/$slug'
      path: '/kamchatka/$slug'
      fullPath: '/kamchatka/$slug'
      preLoaderRoute: typeof KamchatkaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof BookingRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guests': {
      id: '/admin/guests'
      path: '/guests'
      fullPath: '/admin/guests'
      preLoaderRoute: typeof AdminGuestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site/': {
      id: '/admin/site/'
      path: '/'
      fullPath: '/admin/site/'
      preLoaderRoute: typeof AdminSiteIndexRouteImport
      parentRoute: typeof AdminSiteRoute
    }
    '/booking/voucher/$id': {
      id: '/booking/voucher/$id'
      path: '/voucher/$id'
      fullPath: '/booking/voucher/$id'
      preLoaderRoute: typeof BookingVoucherIdRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/pay/$id': {
      id: '/booking/pay/$id'
      path: '/pay/$id'
      fullPath: '/booking/pay/$id'
      preLoaderRoute: typeof BookingPayIdRouteImport
      parentRoute: typeof BookingRoute
    }
    '/booking/chat/$id': {
      id: '/booking/chat/$id'
      path: '/chat/$id'
      fullPath: '/booking/chat/$id'
      preLoaderRoute: typeof BookingChatIdRouteImport
      parentRoute: typeof BookingRoute
    }
    '/api/telegram/webhook': {
      id: '/api/telegram/webhook'
      path: '/api/telegram/webhook'
      fullPath: '/api/telegram/webhook'
      preLoaderRoute: typeof ApiTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/travelline-test': {
      id: '/api/public/travelline-test'
      path: '/api/public/travelline-test'
      fullPath: '/api/public/travelline-test'
      preLoaderRoute: typeof ApiPublicTravellineTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alfa-callback': {
      id: '/api/public/alfa-callback'
      path: '/api/public/alfa-callback'
      fullPath: '/api/public/alfa-callback'
      preLoaderRoute: typeof ApiPublicAlfaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/cron-tl-sync': {
      id: '/api/internal/cron-tl-sync'
      path: '/api/internal/cron-tl-sync'
      fullPath: '/api/internal/cron-tl-sync'
      preLoaderRoute: typeof ApiInternalCronTlSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/cron-reminders': {
      id: '/api/internal/cron-reminders'
      path: '/api/internal/cron-reminders'
      fullPath: '/api/internal/cron-reminders'
      preLoaderRoute: typeof ApiInternalCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/site/services': {
      id: '/admin/site/services'
      path: '/services'
      fullPath: '/admin/site/services'
      preLoaderRoute: typeof AdminSiteServicesRouteImport
      parentRoute: typeof AdminSiteRoute
    }
    '/admin/site/home': {
      id: '/admin/site/home'
      path: '/home'
      fullPath: '/admin/site/home'
      preLoaderRoute: typeof AdminSiteHomeRouteImport
      parentRoute: typeof AdminSiteRoute
    }
    '/admin/site/about': {
      id: '/admin/site/about'
      path: '/about'
      fullPath: '/admin/site/about'
      preLoaderRoute: typeof AdminSiteAboutRouteImport
      parentRoute: typeof AdminSiteRoute
    }
    '/api/public/voucher/$id': {
      id: '/api/public/voucher/$id'
      path: '/api/public/voucher/$id'
      fullPath: '/api/public/voucher/$id'
      preLoaderRoute: typeof ApiPublicVoucherIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminSiteRouteChildren {
  AdminSiteAboutRoute: typeof AdminSiteAboutRoute
  AdminSiteHomeRoute: typeof AdminSiteHomeRoute
  AdminSiteServicesRoute: typeof AdminSiteServicesRoute
  AdminSiteIndexRoute: typeof AdminSiteIndexRoute
}

const AdminSiteRouteChildren: AdminSiteRouteChildren = {
  AdminSiteAboutRoute: AdminSiteAboutRoute,
  AdminSiteHomeRoute: AdminSiteHomeRoute,
  AdminSiteServicesRoute: AdminSiteServicesRoute,
  AdminSiteIndexRoute: AdminSiteIndexRoute,
}

const AdminSiteRouteWithChildren = AdminSiteRoute._addFileChildren(
  AdminSiteRouteChildren,
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminGuestsRoute: typeof AdminGuestsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSiteRoute: typeof AdminSiteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminGuestsRoute: AdminGuestsRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSiteRoute: AdminSiteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BookingRouteChildren {
  BookingSuccessRoute: typeof BookingSuccessRoute
  BookingChatIdRoute: typeof BookingChatIdRoute
  BookingPayIdRoute: typeof BookingPayIdRoute
  BookingVoucherIdRoute: typeof BookingVoucherIdRoute
}

const BookingRouteChildren: BookingRouteChildren = {
  BookingSuccessRoute: BookingSuccessRoute,
  BookingChatIdRoute: BookingChatIdRoute,
  BookingPayIdRoute: BookingPayIdRoute,
  BookingVoucherIdRoute: BookingVoucherIdRoute,
}

const BookingRouteWithChildren =
  BookingRoute._addFileChildren(BookingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  BookingRoute: BookingRouteWithChildren,
  ContactsRoute: ContactsRoute,
  LoginRoute: LoginRoute,
  RoomsRoute: RoomsRoute,
  ServicesRoute: ServicesRoute,
  SignupRoute: SignupRoute,
  WellnessRoute: WellnessRoute,
  KamchatkaSlugRoute: KamchatkaSlugRoute,
  KamchatkaIndexRoute: KamchatkaIndexRoute,
  ApiInternalCronRemindersRoute: ApiInternalCronRemindersRoute,
  ApiInternalCronTlSyncRoute: ApiInternalCronTlSyncRoute,
  ApiPublicAlfaCallbackRoute: ApiPublicAlfaCallbackRoute,
  ApiPublicTravellineTestRoute: ApiPublicTravellineTestRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  ApiPublicVoucherIdRoute: ApiPublicVoucherIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
