/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WellnessRouteImport } from './routes/wellness'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KamchatkaIndexRouteImport } from './routes/kamchatka.index'
import { Route as KamchatkaSlugRouteImport } from './routes/kamchatka.$slug'
import { Route as BookingSuccessRouteImport } from './routes/booking.success'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as BookingPayIdRouteImport } from './routes/booking.pay.$id'
import { Route as ApiPublicAlfaCallbackRouteImport } from './routes/api/public/alfa-callback'

const WellnessRoute = WellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamchatkaIndexRoute = KamchatkaIndexRouteImport.update({
  id: '/kamchatka/',
  path: '/kamchatka/',
  getParentRoute: () => rootRouteImport,
} as any)
const KamchatkaSlugRoute = KamchatkaSlugRouteImport.update({
  id: '/kamchatka/$slug',
  path: '/kamchatka/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => BookingRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingPayIdRoute = BookingPayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => BookingRoute,
} as any)
const ApiPublicAlfaCallbackRoute = ApiPublicAlfaCallbackRouteImport.update({
  id: '/api/public/alfa-callback',
  path: '/api/public/alfa-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/booking': typeof BookingRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/rooms': typeof RoomsRoute
  '/services': typeof ServicesRoute
  '/wellness': typeof WellnessRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/booking/success': typeof BookingSuccessRoute
  '/kamchatka/$slug': typeof KamchatkaSlugRoute
  '/kamchatka/': typeof KamchatkaIndexRoute
  '/api/public/alfa-callback': typeof ApiPublicAlfaCallbackRoute
  '/booking/pay/$id': typeof BookingPayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/booking': typeof BookingRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/rooms': typeof RoomsRoute
  '/services': typeof ServicesRoute
  '/wellness': typeof WellnessRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/booking/success': typeof BookingSuccessRoute
  '/kamchatka/$slug': typeof KamchatkaSlugRoute
  '/kamchatka': typeof KamchatkaIndexRoute
  '/api/public/alfa-callback': typeof ApiPublicAlfaCallbackRoute
  '/booking/pay/$id': typeof BookingPayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/booking': typeof BookingRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/login': typeof LoginRoute
  '/rooms': typeof RoomsRoute
  '/services': typeof ServicesRoute
  '/wellness': typeof WellnessRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/booking/success': typeof BookingSuccessRoute
  '/kamchatka/$slug': typeof KamchatkaSlugRoute
  '/kamchatka/': typeof KamchatkaIndexRoute
  '/api/public/alfa-callback': typeof ApiPublicAlfaCallbackRoute
  '/booking/pay/$id': typeof BookingPayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/booking'
    | '/contacts'
    | '/login'
    | '/rooms'
    | '/services'
    | '/wellness'
    | '/admin/bookings'
    | '/booking/success'
    | '/kamchatka/$slug'
    | '/kamchatka/'
    | '/api/public/alfa-callback'
    | '/booking/pay/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/booking'
    | '/contacts'
    | '/login'
    | '/rooms'
    | '/services'
    | '/wellness'
    | '/admin/bookings'
    | '/booking/success'
    | '/kamchatka/$slug'
    | '/kamchatka'
    | '/api/public/alfa-callback'
    | '/booking/pay/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/booking'
    | '/contacts'
    | '/login'
    | '/rooms'
    | '/services'
    | '/wellness'
    | '/admin/bookings'
    | '/booking/success'
    | '/kamchatka/$slug'
    | '/kamchatka/'
    | '/api/public/alfa-callback'
    | '/booking/pay/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BookingRoute: typeof BookingRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  LoginRoute: typeof LoginRoute
  RoomsRoute: typeof RoomsRoute
  ServicesRoute: typeof ServicesRoute
  WellnessRoute: typeof WellnessRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  KamchatkaSlugRoute: typeof KamchatkaSlugRoute
  KamchatkaIndexRoute: typeof KamchatkaIndexRoute
  ApiPublicAlfaCallbackRoute: typeof ApiPublicAlfaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wellness': {
      id: '/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof WellnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamchatka/': {
      id: '/kamchatka/'
      path: '/kamchatka'
      fullPath: '/kamchatka/'
      preLoaderRoute: typeof KamchatkaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamchatka/$slug': {
      id: '/kamchatka/$slug'
      path: '/kamchatka/$slug'
      fullPath: '/kamchatka/$slug'
      preLoaderRoute: typeof KamchatkaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/success': {
      id: '/booking/success'
      path: '/success'
      fullPath: '/booking/success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof BookingRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/pay/$id': {
      id: '/booking/pay/$id'
      path: '/pay/$id'
      fullPath: '/booking/pay/$id'
      preLoaderRoute: typeof BookingPayIdRouteImport
      parentRoute: typeof BookingRoute
    }
    '/api/public/alfa-callback': {
      id: '/api/public/alfa-callback'
      path: '/api/public/alfa-callback'
      fullPath: '/api/public/alfa-callback'
      preLoaderRoute: typeof ApiPublicAlfaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BookingRouteChildren {
  BookingSuccessRoute: typeof BookingSuccessRoute
  BookingPayIdRoute: typeof BookingPayIdRoute
}

const BookingRouteChildren: BookingRouteChildren = {
  BookingSuccessRoute: BookingSuccessRoute,
  BookingPayIdRoute: BookingPayIdRoute,
}

const BookingRouteWithChildren =
  BookingRoute._addFileChildren(BookingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BookingRoute: BookingRouteWithChildren,
  ContactsRoute: ContactsRoute,
  LoginRoute: LoginRoute,
  RoomsRoute: RoomsRoute,
  ServicesRoute: ServicesRoute,
  WellnessRoute: WellnessRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  KamchatkaSlugRoute: KamchatkaSlugRoute,
  KamchatkaIndexRoute: KamchatkaIndexRoute,
  ApiPublicAlfaCallbackRoute: ApiPublicAlfaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
